In [ ]:
# from google.colab import drive # Mount the google drive for data loading
# drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np #helps for array operation
import matplotlib.pyplot as plt #helps with graphical plots
import pandas as pd #helps to read the data
from sklearn.model_selection import train_test_split #helps to split training data and testing data
from sklearn.preprocessing import LabelEncoder #helps to encode bool/text variables to be numerical values
from sklearn.preprocessing import OneHotEncoder #helps for label one-hot encoding 
from sklearn.metrics import accuracy_score #helps to evaluate the prediction accuracy
import keras #helps for ANN model construction
import tensorflow as tf #helps for ANN model construction
from sklearn.linear_model import LogisticRegression

In [ ]:
# Load the train and test set gotten from R

train = pd.read_csv('loan_df_train.csv')  #Load data with the corresponding path in google drive 
test = pd.read_csv('loan_df_test.csv')

In [ ]:
# Checking the shape of the data
print (train.shape)
print (test.shape)

(93076, 26)
(40424, 26)


In [ ]:
train.head(6)

Unnamed: 0 loan_limit             Gender  approv_in_adv loan_type  \
0           1         cf  Sex Not Available          False     type1   
1           3         cf               Male           True     type1   
2           4         cf               Male          False     type1   
3           7         cf              Joint           True     type1   
4          10         cf  Sex Not Available          False     type3   
5          11         cf               Male          False     type2   

  loan_purpose Credit_Worthiness  open_credit  business_or_commercial  term  \
0           p1                l1        False                   False   360   
1           p1                l1        False                   False   360   
2           p4                l1        False                   False   360   
3           p3                l1        False                   False   360   
4           p3                l1        False                   False   360   
5           p3                l2        False                    True   300   

   ...  co.applicant_credit_type    age  submission_of_application Region  \
0  ...                       CIB  25-34                    to_inst  south   
1  ...                       CIB  35-44                    to_inst  south   
2  ...                       CIB  45-54                   not_inst  North   
3  ...                       EXP  55-64                    to_inst  North   
4  ...                       EXP  55-64                    to_inst  south   
5  ...                       CIB  55-64                    to_inst  North   

   Status       PC1       PC2       PC3       PC4       PC5  
0       1 -1.850068  2.037221  1.407489  0.303505 -0.652859  
1       0  0.865098 -0.823742  1.034808 -0.639215 -1.060659  
2       0  1.611407 -1.453982  0.493500 -0.104344  0.917519  
3       0 -0.629259 -1.017290  0.193712 -0.703943 -0.999857  
4       0  1.990332  1.011154 -0.720451 -0.086879 -0.799802  
5       1 -1.562589  0.432954  0.743070 -0.253294 -0.277812  

[6 rows x 26 columns]

In [ ]:
test.head(6)

Unnamed: 0 loan_limit Gender  approv_in_adv loan_type loan_purpose  \
0           2         cf   Male          False     type2           p1   
1           5         cf  Joint           True     type1           p1   
2           6         cf  Joint           True     type1           p1   
3           9         cf  Joint          False     type1           p3   
4          14         cf  Joint          False     type2           p4   
5          17         cf  Joint          False     type2           p1   

  Credit_Worthiness  open_credit  business_or_commercial  term  ...  \
0                l1        False                    True   360  ...   
1                l1        False                   False   360  ...   
2                l1        False                   False   360  ...   
3                l1        False                   False   360  ...   
4                l1        False                    True   360  ...   
5                l1        False                    True   360  ...   

   co.applicant_credit_type    age  submission_of_application   Region  \
0                       EXP  55-64                    to_inst    North   
1                       EXP  25-34                   not_inst    North   
2                       EXP  35-44                   not_inst    North   
3                       EXP  55-64                    to_inst  central   
4                       EXP  55-64                    to_inst    North   
5                       EXP  25-34                   not_inst    North   

   Status       PC1       PC2       PC3       PC4       PC5  
0       1 -0.376181  0.330490 -0.815384  0.973283  0.814093  
1       0  2.802043 -0.948997  1.639791  0.419858  0.698197  
2       0  3.623846 -0.890824  0.661266 -1.187383 -1.210327  
3       0 -0.350661 -1.362193  0.777788 -0.404502  1.122199  
4       0  0.611866  0.071980  0.577678  1.104020  1.166278  
5       1 -0.405050  0.519451  1.577580  0.107479 -1.320895  

[6 rows x 26 columns]

In [ ]:
# Conversion of the data frame in R, to a .csv added an extra column, so I will remove them 
del train['Unnamed: 0']
del test['Unnamed: 0']

In [ ]:
train.head(6)

loan_limit             Gender  approv_in_adv loan_type loan_purpose  \
0         cf  Sex Not Available          False     type1           p1   
1         cf               Male           True     type1           p1   
2         cf               Male          False     type1           p4   
3         cf              Joint           True     type1           p3   
4         cf  Sex Not Available          False     type3           p3   
5         cf               Male          False     type2           p3   

  Credit_Worthiness  open_credit  business_or_commercial  term  \
0                l1        False                   False   360   
1                l1        False                   False   360   
2                l1        False                   False   360   
3                l1        False                   False   360   
4                l1        False                   False   360   
5                l2        False                    True   300   

   Neg_ammortization  ...  co.applicant_credit_type    age  \
0              False  ...                       CIB  25-34   
1               True  ...                       CIB  35-44   
2              False  ...                       CIB  45-54   
3              False  ...                       EXP  55-64   
4              False  ...                       EXP  55-64   
5               True  ...                       CIB  55-64   

  submission_of_application  Region Status       PC1       PC2       PC3  \
0                   to_inst   south      1 -1.850068  2.037221  1.407489   
1                   to_inst   south      0  0.865098 -0.823742  1.034808   
2                  not_inst   North      0  1.611407 -1.453982  0.493500   
3                   to_inst   North      0 -0.629259 -1.017290  0.193712   
4                   to_inst   south      0  1.990332  1.011154 -0.720451   
5                   to_inst   North      1 -1.562589  0.432954  0.743070   

        PC4       PC5  
0  0.303505 -0.652859  
1 -0.639215 -1.060659  
2 -0.104344  0.917519  
3 -0.703943 -0.999857  
4 -0.086879 -0.799802  
5 -0.253294 -0.277812  

[6 rows x 25 columns]

In [ ]:
test.head(6)

loan_limit Gender  approv_in_adv loan_type loan_purpose Credit_Worthiness  \
0         cf   Male          False     type2           p1                l1   
1         cf  Joint           True     type1           p1                l1   
2         cf  Joint           True     type1           p1                l1   
3         cf  Joint          False     type1           p3                l1   
4         cf  Joint          False     type2           p4                l1   
5         cf  Joint          False     type2           p1                l1   

   open_credit  business_or_commercial  term  Neg_ammortization  ...  \
0        False                    True   360              False  ...   
1        False                   False   360              False  ...   
2        False                   False   360              False  ...   
3        False                   False   360              False  ...   
4        False                    True   360              False  ...   
5        False                    True   360               True  ...   

   co.applicant_credit_type    age submission_of_application   Region Status  \
0                       EXP  55-64                   to_inst    North      1   
1                       EXP  25-34                  not_inst    North      0   
2                       EXP  35-44                  not_inst    North      0   
3                       EXP  55-64                   to_inst  central      0   
4                       EXP  55-64                   to_inst    North      0   
5                       EXP  25-34                  not_inst    North      1   

        PC1       PC2       PC3       PC4       PC5  
0 -0.376181  0.330490 -0.815384  0.973283  0.814093  
1  2.802043 -0.948997  1.639791  0.419858  0.698197  
2  3.623846 -0.890824  0.661266 -1.187383 -1.210327  
3 -0.350661 -1.362193  0.777788 -0.404502  1.122199  
4  0.611866  0.071980  0.577678  1.104020  1.166278  
5 -0.405050  0.519451  1.577580  0.107479 -1.320895  

[6 rows x 25 columns]

In [ ]:
print (train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93076 entries, 0 to 93075
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   loan_limit                 93076 non-null  object 
 1   Gender                     93076 non-null  object 
 2   approv_in_adv              93076 non-null  bool   
 3   loan_type                  93076 non-null  object 
 4   loan_purpose               93076 non-null  object 
 5   Credit_Worthiness          93076 non-null  object 
 6   open_credit                93076 non-null  bool   
 7   business_or_commercial     93076 non-null  bool   
 8   term                       93076 non-null  int64  
 9   Neg_ammortization          93076 non-null  bool   
 10  interest_only              93076 non-null  bool   
 11  lump_sum_payment           93076 non-null  bool   
 12  occupancy_type             93076 non-null  object 
 13  total_units                93076 non-null  int

In [ ]:
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40424 entries, 0 to 40423
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   loan_limit                 40424 non-null  object 
 1   Gender                     40424 non-null  object 
 2   approv_in_adv              40424 non-null  bool   
 3   loan_type                  40424 non-null  object 
 4   loan_purpose               40424 non-null  object 
 5   Credit_Worthiness          40424 non-null  object 
 6   open_credit                40424 non-null  bool   
 7   business_or_commercial     40424 non-null  bool   
 8   term                       40424 non-null  int64  
 9   Neg_ammortization          40424 non-null  bool   
 10  interest_only              40424 non-null  bool   
 11  lump_sum_payment           40424 non-null  bool   
 12  occupancy_type             40424 non-null  object 
 13  total_units                40424 non-null  int

Rearranging the column order so that the target variable is the last column. I will do this for both data frames.

In [ ]:
test = test[["loan_limit", "Gender", "approv_in_adv","loan_type","loan_purpose","Credit_Worthiness","open_credit","business_or_commercial","term","Neg_ammortization","interest_only","lump_sum_payment","occupancy_type","total_units","credit_type","co.applicant_credit_type","age","submission_of_application","Region","PC1","PC2","PC3","PC4","PC5","Status"]]

In [ ]:
train = train[["loan_limit", "Gender", "approv_in_adv","loan_type","loan_purpose","Credit_Worthiness","open_credit","business_or_commercial","term","Neg_ammortization","interest_only","lump_sum_payment","occupancy_type","total_units","credit_type","co.applicant_credit_type","age","submission_of_application","Region","PC1","PC2","PC3","PC4","PC5","Status"]]

In [ ]:
print (train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93076 entries, 0 to 93075
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   loan_limit                 93076 non-null  object 
 1   Gender                     93076 non-null  object 
 2   approv_in_adv              93076 non-null  bool   
 3   loan_type                  93076 non-null  object 
 4   loan_purpose               93076 non-null  object 
 5   Credit_Worthiness          93076 non-null  object 
 6   open_credit                93076 non-null  bool   
 7   business_or_commercial     93076 non-null  bool   
 8   term                       93076 non-null  int64  
 9   Neg_ammortization          93076 non-null  bool   
 10  interest_only              93076 non-null  bool   
 11  lump_sum_payment           93076 non-null  bool   
 12  occupancy_type             93076 non-null  object 
 13  total_units                93076 non-null  int

In [ ]:
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40424 entries, 0 to 40423
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   loan_limit                 40424 non-null  object 
 1   Gender                     40424 non-null  object 
 2   approv_in_adv              40424 non-null  bool   
 3   loan_type                  40424 non-null  object 
 4   loan_purpose               40424 non-null  object 
 5   Credit_Worthiness          40424 non-null  object 
 6   open_credit                40424 non-null  bool   
 7   business_or_commercial     40424 non-null  bool   
 8   term                       40424 non-null  int64  
 9   Neg_ammortization          40424 non-null  bool   
 10  interest_only              40424 non-null  bool   
 11  lump_sum_payment           40424 non-null  bool   
 12  occupancy_type             40424 non-null  object 
 13  total_units                40424 non-null  int

In [ ]:
# Creating copies of the data frames for the sake of redundancy. 
# Just in case something unfortunate happens, it would not affect the main data frame 
train_temp = train.copy()
test_temp = test.copy()

Using a Likelihood encoding method to encode the variables in the data frames

In [ ]:

lb = LabelEncoder()
# would first encode the non-numerical column variables with type object
cat_cols = [col for col in train_temp.columns if train_temp[col].dtype == 'object']

for col in cat_cols:
    train_temp[col] = lb.fit_transform(train_temp[col])

In [ ]:
cat_cols = [col for col in test_temp.columns if test_temp[col].dtype == 'object']

for col in cat_cols:
    test_temp[col] = lb.fit_transform(test_temp[col])

In [ ]:
#function for encoding
def likelihood_encoding(df, cat_cols, target_variable = "Status"):
    # cat_cols.remove(target_variable)
    df_temp = df.copy()
    for col in cat_cols:
        effect = {}
        print(col)
        for category in df[col].unique():
            print(category)

            try:
                temp = df[df[col] == category]
                lr = LogisticRegression()
                X = temp.drop(target_variable, axis = 1, inplace = False)
                y = temp[target_variable]
                # print(temp.drop(target_variable, axis = 1).isnull().sum())
                lr.fit(X, y)

                effect[category] = accuracy_score(y, lr.predict(X))
            except Exception as E:
                print(E)
        
        for key, value in effect.items():
            effect[key] = np.log(effect[key] / (1 - effect[key] + 1e-6))
            
        df_temp.loc[:, col] = df_temp.loc[:, col].map(effect)
    return df_temp

In [ ]:
cat_cols = [col for col in train_temp.columns if train_temp[col].dtype == 'object']
train_temp = likelihood_encoding(train_temp, cat_cols)

In [ ]:
cat_cols = [col for col in test_temp.columns if test_temp[col].dtype == 'object']
test_temp = likelihood_encoding(test_temp, cat_cols)

In [ ]:
train_temp.head()

loan_limit  Gender  approv_in_adv  loan_type  loan_purpose  \
0           0       3          False          0             0   
1           0       2           True          0             0   
2           0       2          False          0             3   
3           0       1           True          0             2   
4           0       3          False          2             2   

   Credit_Worthiness  open_credit  business_or_commercial  term  \
0                  0        False                   False   360   
1                  0        False                   False   360   
2                  0        False                   False   360   
3                  0        False                   False   360   
4                  0        False                   False   360   

   Neg_ammortization  ...  co.applicant_credit_type  age  \
0              False  ...                         0    0   
1               True  ...                         0    1   
2              False  ...                         0    2   
3              False  ...                         1    3   
4              False  ...                         1    3   

   submission_of_application  Region       PC1       PC2       PC3       PC4  \
0                          1       3 -1.850068  2.037221  1.407489  0.303505   
1                          1       3  0.865098 -0.823742  1.034808 -0.639215   
2                          0       0  1.611407 -1.453982  0.493500 -0.104344   
3                          1       0 -0.629259 -1.017290  0.193712 -0.703943   
4                          1       3  1.990332  1.011154 -0.720451 -0.086879   

        PC5  Status  
0 -0.652859       1  
1 -1.060659       0  
2  0.917519       0  
3 -0.999857       0  
4 -0.799802       0  

[5 rows x 25 columns]

In [ ]:
test_temp.head()

loan_limit  Gender  approv_in_adv  loan_type  loan_purpose  \
0           0       2          False          1             0   
1           0       1           True          0             0   
2           0       1           True          0             0   
3           0       1          False          0             2   
4           0       1          False          1             3   

   Credit_Worthiness  open_credit  business_or_commercial  term  \
0                  0        False                    True   360   
1                  0        False                   False   360   
2                  0        False                   False   360   
3                  0        False                   False   360   
4                  0        False                    True   360   

   Neg_ammortization  ...  co.applicant_credit_type  age  \
0              False  ...                         1    3   
1              False  ...                         1    0   
2              False  ...                         1    1   
3              False  ...                         1    3   
4              False  ...                         1    3   

   submission_of_application  Region       PC1       PC2       PC3       PC4  \
0                          1       0 -0.376181  0.330490 -0.815384  0.973283   
1                          0       0  2.802043 -0.948997  1.639791  0.419858   
2                          0       0  3.623846 -0.890824  0.661266 -1.187383   
3                          1       2 -0.350661 -1.362193  0.777788 -0.404502   
4                          1       0  0.611866  0.071980  0.577678  1.104020   

        PC5  Status  
0  0.814093       1  
1  0.698197       0  
2 -1.210327       0  
3  1.122199       0  
4  1.166278       0  

[5 rows x 25 columns]

Encoding objects of the boolean data type


In [ ]:
cat_cols = [col for col in train_temp.columns if train_temp[col].dtype == 'bool']

for col in cat_cols:
    train_temp[col] = lb.fit_transform(train_temp[col])

In [ ]:
cat_cols = [col for col in test_temp.columns if test_temp[col].dtype == 'bool']

for col in cat_cols:
    test_temp[col] = lb.fit_transform(test_temp[col])

In [ ]:
cat_cols = [col for col in train_temp.columns if train_temp[col].dtype == 'bool']
train_temp = likelihood_encoding(train_temp, cat_cols)

In [ ]:
cat_cols = [col for col in test_temp.columns if test_temp[col].dtype == 'bool']
test_temp = likelihood_encoding(test_temp, cat_cols)

In [ ]:
train_temp.iloc[:,19:24]

PC1       PC2       PC3       PC4       PC5
0     -1.850068  2.037221  1.407489  0.303505 -0.652859
1      0.865098 -0.823742  1.034808 -0.639215 -1.060659
2      1.611407 -1.453982  0.493500 -0.104344  0.917519
3     -0.629259 -1.017290  0.193712 -0.703943 -0.999857
4      1.990332  1.011154 -0.720451 -0.086879 -0.799802
...         ...       ...       ...       ...       ...
93071 -0.865507  2.369404  0.369621  0.364381  0.506558
93072 -2.331608 -0.277857  1.064586  0.190716 -1.293338
93073  1.594146  1.039026 -0.541314 -0.095258  0.946234
93074  1.895127  1.213601  0.232417 -1.196620  0.291429
93075 -0.447095  0.575164 -1.006530  1.045988 -0.508231

[93076 rows x 5 columns]

In [ ]:
# Creating a copy of the encoded data frames
train_tp = train_temp.copy()
test_tp = test_temp.copy()

In [ ]:
train_le = np.zeros_like(train_tp)     # create a matrix of zeros in the shape of train_tp and store in train_le     # Set up a matrix for encoded data 
train_le[:,19:24] = train_tp.iloc[:,19:24]      # This selects the all rows from train_le and copies all rows of train_tp into it. and then copies columns 19 to 23 into the train_le
for i in range(1, train_tp.shape[1]):           # Encode the data using label encoder
   le = LabelEncoder().fit(train_tp.iloc[:,i])  #fit first to let the encoder know the distinct numbers
   train_le[:,i] = le.transform(train_tp.iloc[:,i]) # transform to the distinct encoding starting from 0 to n

In [ ]:
print(train_le)

[[0.0000e+00 3.0000e+00 0.0000e+00 ... 5.8091e+04 2.7877e+04 1.0000e+00]
 [0.0000e+00 2.0000e+00 1.0000e+00 ... 2.3629e+04 1.6506e+04 0.0000e+00]
 [0.0000e+00 2.0000e+00 0.0000e+00 ... 4.2695e+04 7.2248e+04 0.0000e+00]
 ...
 [0.0000e+00 3.0000e+00 0.0000e+00 ... 4.3050e+04 7.3084e+04 0.0000e+00]
 [0.0000e+00 2.0000e+00 0.0000e+00 ... 1.0251e+04 5.4278e+04 0.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 7.9465e+04 3.2008e+04 0.0000e+00]]


In [ ]:
test_le = np.zeros_like(test_tp)     
test_le[:,19:24] = test_tp.iloc[:,19:24]       
for i in range(1, test_tp.shape[1]):   
   le = LabelEncoder().fit(test_tp.iloc[:,i])   
   test_le[:,i] = le.transform(test_tp.iloc[:,i])  

In [ ]:
X_train, y_train = train_le[:,:-1], train_le[:,-1:]
X_test, y_test = test_le[:,:-1], test_le[:,-1:]

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(93076, 24)
(40424, 24)
(93076, 1)
(40424, 1)


In [ ]:
onehot = OneHotEncoder()                     #An objective for one-hot package
onehot.fit(y_train)                          #Transform labels to be the one-hot format
y_train_onehot = onehot.transform(y_train).toarray() #Transform training labels to be one-hot format
y_test_onehot = onehot.transform(y_test).toarray()   #Transform testing labels to be one-hot format

In [ ]:
model = keras.Sequential()                         
model.add(keras.layers.Dense(1024, input_shape=(24,))) 
model.add(keras.layers.Activation("sigmoid"))          
model.add(keras.layers.Dense(2))                       
model.add(keras.layers.Activation("softmax"))          
model.compile(tf.keras.optimizers.SGD(learning_rate = 1e-2), 'categorical_crossentropy', metrics='acc')
model.summary()
model.fit(X_train, y_train_onehot, epochs = 75, batch_size = 1024, verbose = 2) #training the model with some hyper-parameters

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1024)              25600     
                                                                 
 activation (Activation)     (None, 1024)              0         
                                                                 
 dense_1 (Dense)             (None, 2)                 2050      
                                                                 
 activation_1 (Activation)   (None, 2)                 0         
                                                                 
Total params: 27,650
Trainable params: 27,650
Non-trainable params: 0
_________________________________________________________________
Epoch 1/75
91/91 - 2s - loss: 0.5496 - acc: 0.7432 - 2s/epoch - 23ms/step
Epoch 2/75
91/91 - 1s - loss: 0.5249 - acc: 0.7539 - 1s/epoch - 13ms/step
Epoch 3/75
91/91 - 1s - loss: 0.5261

In [ ]:
prediction = model.predict(X_test)            # Predict the testing set
print (model.evaluate(X_test, y_test_onehot)) # Evaluation the prediction, and accuracy in the test set is 0.9617

1264/1264 [==============================] - 2s 1ms/step - loss: 0.5241 - acc: 0.7549
[0.5240556001663208, 0.7548980712890625]


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
y_pred=np.argmax(prediction, axis=1)
y_test=np.argmax(y_test_onehot, axis=1)


print(confusion_matrix(y_test, y_pred))

[[30042   299]
 [ 9609   474]]


Model classification report

In [ ]:

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.76      0.99      0.86     30341
           1       0.61      0.05      0.09     10083

    accuracy                           0.75     40424
   macro avg       0.69      0.52      0.47     40424
weighted avg       0.72      0.75      0.67     40424

